/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Ui;

/**
 *
 * @author winJV
 */
public class InsertVarios {
        public String[] getInsert_rols() {
        return new String [] {
            "INSERT INTO umg_rols (id_rol,nombre,descripcion) VALUES (1,'Administrador','Rol de Administrador con descripcion acerca de que hace.')",
            "INSERT INTO umg_rols (id_rol,nombre,descripcion) VALUES (2,'Gerente','Rol de Gerente con descripcion acerca de que hace.')",
            "INSERT INTO umg_rols (id_rol,nombre,descripcion) VALUES (3,'Supervisor','Rol de Supervisor con descripcion acerca de que hace.')",
            "INSERT INTO umg_rols (id_rol,nombre,descripcion) VALUES (4,'Cajero Matutino','Rol de Cajero Matutino con descripcion acerca de que hace.')",
            "INSERT INTO umg_rols (id_rol,nombre,descripcion) VALUES (5,'Cajero Nocturno','Rol de Cajero Nocturno con descripcion acerca de que hace.')",
            "INSERT INTO umg_rols (id_rol,nombre,descripcion) VALUES (6,'Practicante','Rol de Practicante con descripcion acerca de que hace.')"
        };
    }

    public String[] getInsert_usuarios() {
        return new String [] {
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Romero','lucia_romero@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Rebeca Flores','rebeca_flores@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Javier Mazariegos','javier_mazariegos@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ruth Dias','ruth_dias@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Alejandro Ruiz','alejandro_ruiz@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ruth Rojas','ruth_rojas@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Sofia Mazariegos','sofia_mazariegos@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Stefani Dominguez','stefani_dominguez@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Diego Flores','diego_flores@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Aguirre','lucia_aguirre@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Rebeca Torres','rebeca_torres@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Juan Castillo','juan_castillo@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Rebeca Lopez','rebeca_lopez@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Martinez','lucia_martinez@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Angel Carranza','angel_carranza@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Antonio Piedrasanta','antonio_piedrasanta@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Alejandro Romero','alejandro_romero@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Juan Cordoba','juan_cordoba@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Angeles Barrios','angeles_barrios@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ricardo Castillo','ricardo_castillo@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('William Dias','william_dias@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Hector Rodriguez','hector_rodriguez@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Antonio Fernandez','antonio_fernandez@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Recinos','lucia_recinos@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Veronica Piedrasanta','veronica_piedrasanta@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('William Sosa','william_sosa@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Alejandro Flores','alejandro_flores@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Susana Flores','susana_flores@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Pedro Alvarado','pedro_alvarado@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Sofia Giron','sofia_giron@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Angel Monterroso','angel_monterroso@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Susana Sosa','susana_sosa@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ismael Ramirez','ismael_ramirez@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Armando Carranza','armando_carranza@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Aaron Romero','aaron_romero@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Carmen Barrios','carmen_barrios@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Oscar Marquez','oscar_marquez@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Noemi Aguirre','noemi_aguirre@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Jose Sosa','jose_sosa@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('David Lopez','david_lopez@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Maribel Alvarez','maribel_alvarez@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Vladimir Martinez','vladimir_martinez@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Maribel Aguirre','maribel_aguirre@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Daniela Gomez','daniela_gomez@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Pedro Giron','pedro_giron@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Angel Rodriguez','angel_rodriguez@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Sofia Marquez','sofia_marquez@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Pedro Cordoba','pedro_cordoba@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Aaron Ramirez','aaron_ramirez@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ivan Ruiz','ivan_ruiz@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Aaron Rabanales','aaron_rabanales@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Castillo','lucia_castillo@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Daniela Alvarez','daniela_alvarez@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Armando Castillo','armando_castillo@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Oscar Torres','oscar_torres@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Diego Alvarado','diego_alvarado@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Jose Romero','jose_romero@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('William Recinos','william_recinos@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('David Martinez','david_martinez@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Aaron Martinez','aaron_martinez@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('David Monterroso','david_monterroso@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Antonio Siguenza','antonio_siguenza@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Sofia Rodriguez','sofia_rodriguez@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Susana Cordoba','susana_cordoba@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ruth Carranza','ruth_carranza@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Maria Marquez','maria_marquez@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Jose Romero','jose_romero@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Maribel Jimenez','maribel_jimenez@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ismael Mazariegos','ismael_mazariegos@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Antonio Carranza','antonio_carranza@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ricardo Barrios','ricardo_barrios@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Ruiz','lucia_ruiz@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Rebeca Alvarez','rebeca_alvarez@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Angeles Recinos','angeles_recinos@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Javier Gutierrez','javier_gutierrez@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Aaron Monterroso','aaron_monterroso@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('William Castellanos','william_castellanos@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Daniela Perez','daniela_perez@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Pedro Martinez','pedro_martinez@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Rebeca Giron','rebeca_giron@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Aaron Gonzalez','aaron_gonzalez@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Luz Marquez','luz_marquez@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Gutierrez','lucia_gutierrez@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Natalia Aguirre','natalia_aguirre@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Vladimir Aguirre','vladimir_aguirre@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Diego Gutierrez','diego_gutierrez@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ivan Lopez','ivan_lopez@miumg.edu.gt','MTIzNDU=',2)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Angel Romero','angel_romero@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Juan Jimenez','juan_jimenez@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Luz Gutierrez','luz_gutierrez@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ismael Recinos','ismael_recinos@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Gonzalez','lucia_gonzalez@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Maribel Romero','maribel_romero@miumg.edu.gt','MTIzNDU=',5)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Susana Carranza','susana_carranza@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Veronica Rojas','veronica_rojas@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Daniela Lopez','daniela_lopez@miumg.edu.gt','MTIzNDU=',3)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Angeles Rabanales','angeles_rabanales@miumg.edu.gt','MTIzNDU=',1)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Carolina Castro','carolina_castro@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Stefani Giron','stefani_giron@miumg.edu.gt','MTIzNDU=',4)",
            "INSERT INTO umg_usuarios (nombre, correo_acceso, pw, rol) VALUES ('Estrella Mazariegos','estrella_mazariegos@miumg.edu.gt','MTIzNDU=',3)"
        };
    }

    public String[] getInsert_unidades_medida() {
        return new String [] {
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Onza')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Libra')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Arroba')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Kilogramo')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Gramo')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Miligramo')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Tonelada')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Sixpack')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Lata')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Botella')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Caja')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Docena')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Decena')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Ciento')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Centimetro')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Galon')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Pie')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Pulgadas')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Yarda')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Arroba')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Litro')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Medio Litro')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Duo Pack')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Pieza')",
            "INSERT INTO umg_unidades_medida (nombre) VALUES ('Kit')"
        };
    }

    public String[] getInsert_proveedores() {
        return new String [] {
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Malher','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Cerveceria Centroamericana','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Adeph','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Cruz Verde','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Farmacias del Ahorro','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Wallmart','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Paiz','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Despensa Familiar','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Toyota','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Mazda','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Hyundai','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Bodega Central','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('ADOC','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Par Dos','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Gallo','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Unilever','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Colgate','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Coca Cola','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('McDonalds','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Burger King','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Wendys','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Pepsi','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Dos Pinos','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Quaker','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Pozuelo','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Protex','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Bimbo','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Axion','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Bremen','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Tang','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Nescafe','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Musum','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Ina','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Salvavidas','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Charles','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Tacorazon','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('HP','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Dell','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('MSI','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Aorus','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Lenovo','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Kingston','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('XPG','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Corsair','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Cooler Master','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Adata','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('EVGA','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Razer','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Logitech','Ciudad de Guatemala',0)",
            "INSERT INTO umg_proveedores (nombre, direccion, telefono) VALUES ('Asus','Ciudad de Guatemala',0)"
        };
    }

    public String[] getInsert_productos() {
        return new String [] {
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Leche en Polvo',20,'Descripcion generica del producto Leche en Polvo',19,39)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Spaguetti',48,'Descripcion generica del producto Spaguetti',2,104)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Leche Liquida',9,'Descripcion generica del producto Leche Liquida',13,10)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Tomate',16,'Descripcion generica del producto Tomate',20,56)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Cebolla',34,'Descripcion generica del producto Cebolla',23,172)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Detergente',1,'Descripcion generica del producto Detergente',14,176)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Aceite Vegetal',1,'Descripcion generica del producto Aceite Vegetal',24,188)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Suero',34,'Descripcion generica del producto Suero',20,134)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Pasta',39,'Descripcion generica del producto Pasta',15,81)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Queso',38,'Descripcion generica del producto Queso',3,163)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Coca Cola',30,'Descripcion generica del producto Coca Cola',9,122)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Fanta',30,'Descripcion generica del producto Fanta',13,67)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Pepsi',38,'Descripcion generica del producto Pepsi',6,73)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Aspirina',9,'Descripcion generica del producto Aspirina',23,52)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Licor',20,'Descripcion generica del producto Licor',20,128)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Laptop',16,'Descripcion generica del producto Laptop',1,36)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Memoria USB',38,'Descripcion generica del producto Memoria USB',1,196)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Memoria RAM',23,'Descripcion generica del producto Memoria RAM',10,140)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Disco Solido',47,'Descripcion generica del producto Disco Solido',10,106)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Espatula de Cocina',48,'Descripcion generica del producto Espatula de Cocina',14,181)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Ventilador de PC',24,'Descripcion generica del producto Ventilador de PC',10,187)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('CD para grabar en pc',34,'Descripcion generica del producto CD para grabar en pc',2,96)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('DVD para grabar en pc',42,'Descripcion generica del producto DVD para grabar en pc',13,133)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Ron',34,'Descripcion generica del producto Ron',1,111)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Cerveza',3,'Descripcion generica del producto Cerveza',15,59)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Pasta Dental',28,'Descripcion generica del producto Pasta Dental',20,164)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Jugo de Vegetales',26,'Descripcion generica del producto Jugo de Vegetales',25,125)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Tortillitas SeÃ±orial',26,'Descripcion generica del producto Tortillitas SeÃ±orial',23,178)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Chocolate Hershey',7,'Descripcion generica del producto Chocolate Hershey',2,10)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Galleta',40,'Descripcion generica del producto Galleta',7,84)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Jugo de Manzana',47,'Descripcion generica del producto Jugo de Manzana',12,190)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Agua Oxigenada',12,'Descripcion generica del producto Agua Oxigenada',14,143)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Sal de Cocina',41,'Descripcion generica del producto Sal de Cocina',22,155)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Mesa Desplegable',41,'Descripcion generica del producto Mesa Desplegable',10,139)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Pelota Inflable',4,'Descripcion generica del producto Pelota Inflable',16,52)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Pescado en bandeja',29,'Descripcion generica del producto Pescado en bandeja',6,101)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Pollo en bandeja',45,'Descripcion generica del producto Pollo en bandeja',11,0)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Res en Bandeja',13,'Descripcion generica del producto Res en Bandeja',15,156)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Tablayeso',29,'Descripcion generica del producto Tablayeso',14,26)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Madera de Roble',45,'Descripcion generica del producto Madera de Roble',11,136)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Madera de Pino',47,'Descripcion generica del producto Madera de Pino',7,126)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Cartulina',14,'Descripcion generica del producto Cartulina',13,196)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Pintura para Hogar',48,'Descripcion generica del producto Pintura para Hogar',7,84)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Acuarela',19,'Descripcion generica del producto Acuarela',21,128)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Tempera',41,'Descripcion generica del producto Tempera',4,112)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Lapiz de Grafito',8,'Descripcion generica del producto Lapiz de Grafito',9,66)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Lapicero de Colores',50,'Descripcion generica del producto Lapicero de Colores',12,173)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Mesa de Madera',26,'Descripcion generica del producto Mesa de Madera',8,92)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Impresora Multifuncional',41,'Descripcion generica del producto Impresora Multifuncional',15,178)",
            "INSERT INTO umg_productos (nombre_comercial, proveedor, descripcion, unidad_medida, precio_unitario) VALUES ('Celular',4,'Descripcion generica del producto Celular',21,62)"
        };
    }

    public String[] getInsert_categorias() {
        return new String [] {
            "INSERT INTO umg_categorias (descripcion) VALUES ('Bebidas alcoholicas')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Cerveza')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Cocteles listos')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Ron')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Whisky')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Vino')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Pollo')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('AtÃºn enlatado')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Carne de hamburguesa de res/pollo para cocinar en casa')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Carnes')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Chorizo')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('JamÃ³n')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Mortadela')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Salchicha')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('SalchichÃ³n')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Comida congelada para calentar y consumir')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Comidas rÃ¡pidas')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Huevo')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Batidos')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Crema de leche')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Leche en polvo')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Leche lÃ­quida de vaca')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Leche saborizada')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Quesos')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Yogurt')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Mayonesa')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Mostaza')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Salsa de tomate')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Sopas instantÃ¡neas / deshidratadas o en polvo')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Agua')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Avena envasada lista para consumir')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Bebidas energizantes')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Bebidas hidratantes')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('CafÃ© intantÃ¡neo')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('CafÃ© molido')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Chocolate en pastilla')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Chocolate instantÃ¡neo')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Coladas')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Endulzantes')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Gaseosas')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Jugo de naranja')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Maltas')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Refrescos en polvo')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('TÃ© en bolsa')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('TÃ© lÃ­quido')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Galletas de sal')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Galletas dulces (Waffer, con crema y sin crema, cubiertas de chocolate)')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Galletas saludables (integrales)')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Gelatina en polvo para preparar en casa')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Gelatina lista (ya viene pre-parada)')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Papas fritas de paquetes')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('LoterÃ­as')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('AnalgÃ©sicos (medicamentos para el dolor)')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('AntiÃ¡cidos')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Antigripales(medicamentos contra la gripe)')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Pastas')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Tecnologia')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Cigarrillos')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Aparatos de video')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Audio portatil')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Electrodomesticos - grandes para el hogar')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Electrodomesticos pequeÃ±os para el hogar')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Video juegos')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Caldo de pastilla/polvo')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Condimentos')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Sal')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Arequipe')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Bombones (con o sin chicle')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Chicles')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Chocolates')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Dulces caramelo')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Gomas')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Helados')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Mentas')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Mermelada')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Postres listos para consumir (empacados con marca)')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Arroz')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Cereales (para el desayuno)')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Mezcla (harina) lista para hacer arepas')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Pan empacado')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Pan fresco, de panaderÃ­a (diferente al pan empacado)')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Insecticidas')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Vitaminas / suplementos')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('anticonceptivas')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Preservativos')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Crema especializada para la cara')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Crema (lÃ­quida) Humectante para el cuerpo')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Cremas para afeitar')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Cepillos dentales')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Toallas higiÃ©nicas')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Desodorante')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('JabÃ³n de tocador (en barra, lÃ­quido o espuma)')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('PaÃ±uelos desechables')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Papel higiÃ©nico')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Shampoo')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Tratamiento para la caida del cabello')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Alimento industrializado para gatos')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Alimento industrializado para perros')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Productos para el cuidado de mascotas')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('PaÃ±ales desechables para niÃ±os')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Leche especializadapara bebes')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Motos')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Ambientadores (diferentes a velas aromÃ¡ticas e incienso)')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Blanqueadores')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Detergentes')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('JabÃ³n en barra para lavar ropa')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('JabÃ³n lavaplatos')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Limpiador lÃ­quido para baÃ±os')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Limpiador lÃ­quido para pisos')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Suavisante para ropa')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Servilletas')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Toallas desechables de papel para cocina')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('Esponjillas para lavar platos')",
            "INSERT INTO umg_categorias (descripcion) VALUES ('PaÃ±os absorventes')"
        };
    }

    public String[] getInsert_existencias() {
        return new String [] {
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (1, 291, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),27)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (2, 374, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),23)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (3, 422, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),32)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (4, 424, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),29)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (5, 326, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),52)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (6, 424, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),97)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (7, 414, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),67)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (8, 446, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),22)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (9, 414, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),4)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (10, 412, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),89)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (11, 385, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),99)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (12, 344, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),8)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (13, 332, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),62)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (14, 422, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),68)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (15, 304, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),96)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (16, 342, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),27)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (17, 323, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),35)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (18, 373, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),14)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (19, 338, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),51)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (20, 487, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),44)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (21, 382, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),84)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (22, 406, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),37)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (23, 401, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),51)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (24, 352, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),71)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (25, 409, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),30)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (26, 294, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),68)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (27, 487, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),99)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (28, 429, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),27)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (29, 388, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),89)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (30, 455, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),15)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (31, 423, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),20)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (32, 405, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),28)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (33, 441, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),65)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (34, 346, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),16)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (35, 443, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),51)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (36, 297, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),10)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (37, 425, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),16)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (38, 446, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),50)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (39, 254, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),18)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (40, 438, TO_DATE('2021-09-17 13:00:09', 'yyyy-mm-dd hh24:mi:ss'),38)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (41, 365, TO_DATE('2021-09-17 13:00:10', 'yyyy-mm-dd hh24:mi:ss'),43)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (42, 389, TO_DATE('2021-09-17 13:00:10', 'yyyy-mm-dd hh24:mi:ss'),5)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (43, 472, TO_DATE('2021-09-17 13:00:10', 'yyyy-mm-dd hh24:mi:ss'),58)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (44, 409, TO_DATE('2021-09-17 13:00:10', 'yyyy-mm-dd hh24:mi:ss'),84)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (45, 379, TO_DATE('2021-09-17 13:00:10', 'yyyy-mm-dd hh24:mi:ss'),37)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (46, 409, TO_DATE('2021-09-17 13:00:10', 'yyyy-mm-dd hh24:mi:ss'),53)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (47, 369, TO_DATE('2021-09-17 13:00:10', 'yyyy-mm-dd hh24:mi:ss'),99)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (48, 404, TO_DATE('2021-09-17 13:00:10', 'yyyy-mm-dd hh24:mi:ss'),98)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (49, 449, TO_DATE('2021-09-17 13:00:10', 'yyyy-mm-dd hh24:mi:ss'),59)",
            "INSERT INTO umg_existencias (id_producto, cantidad, adquirido, responsable) VALUES (50, 423, TO_DATE('2021-09-17 13:00:10', 'yyyy-mm-dd hh24:mi:ss'),83)"
        };
    }

    public String[] getInsert_clientes() {
        return new String [] {
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('David Carranza','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Susana Alvarado','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Juan Lopez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Juan Cordoba','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Susana Flores','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angeles Monzon','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Natalia Perez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angeles Martinez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Carmen Alvarado','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Armando Romero','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Noemi Dominguez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Alejandro Lopez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Juan Siguenza','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Stefani Gomez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Juan Alvarez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Pedro Fernandez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Ivan Alvarez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angeles Flores','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angel Piedrasanta','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Maria Flores','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Stefani Rabanales','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Hector Romero','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Jose Mazariegos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Alejandro Piedrasanta','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Alejandro Martinez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Rebeca Mazariegos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Lucia Recinos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Ricardo Barrios','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Ricardo Sosa','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angeles Cordoba','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Lucia Ruiz','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Susana Romero','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Aaron Santos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('David Monzon','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Aaron Aguirre','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angeles Sosa','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Veronica Castellanos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Ricardo Cordoba','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Luz Ramirez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Veronica Aguirre','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Jose Giron','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Veronica Martinez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Noemi Monzon','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Natalia Ramirez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('William Carranza','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Diego Marquez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('William Flores','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Carmen Giron','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Carolina Marquez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angeles Siguenza','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Diego Monterroso','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angel Ruiz','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Juan Alvarado','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Juan Torres','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Maria Rodriguez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('William Cordoba','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Susana Alvarez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Daniela Siguenza','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Carolina Siguenza','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Alejandro Gutierrez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Pedro Castellanos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Ismael Ruiz','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Jose Romero','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Vladimir Ramirez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Aaron Mazariegos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Sofia Gomez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Oscar Sosa','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Alejandro Aguirre','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Juan Mazariegos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Estrella Monzon','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Daniela Perez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Daniela Santos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Hector Castillo','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Sofia Santos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Pedro Perez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Pedro Ruiz','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Ruth Dias','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angel Alvarado','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Lucia Gutierrez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Vladimir Torres','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Vladimir Recinos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Ivan Rojas','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Juan Monzon','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Susana Dias','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Vladimir Ramirez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Antonio Alvarado','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Carolina Castillo','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angel Monterroso','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Pedro Fernandez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angel Monterroso','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('William Alvarez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angel Gonzalez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Rebeca Alvarado','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Luz Jimenez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Aaron Aguirre','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Luz Flores','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('William Rabanales','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Susana Jimenez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Ruth Aguirre','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Carolina Gonzalez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angel Alvarado','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Hector Romero','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Diego Monzon','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Ruth Castillo','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Diego Mazariegos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Hector Mazariegos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Maribel Torres','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Stefani Dias','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Veronica Ruiz','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Jose Sosa','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angel Ramirez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Susana Gutierrez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Diego Recinos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Veronica Gomez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Diego Carranza','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Aaron Dias','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Antonio Perez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Aaron Alvarez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Maribel Sosa','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('David Cordoba','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Natalia Piedrasanta','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Ruth Mazariegos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angel Torres','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Ismael Marquez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Kimberly Romero','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Estrella Marquez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Antonio Cordoba','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Kimberly Ruiz','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Antonio Gonzalez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Carmen Gomez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Hector Flores','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Angel Sosa','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Maria Gomez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Maria Castro','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Vladimir Monzon','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Javier Alvarez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Carolina Mazariegos','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Susana Rodriguez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Maribel Ruiz','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Maria Castillo','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('William Rodriguez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Vladimir Castillo','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Armando Aguirre','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Jose Romero','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Estrella Rabanales','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Antonio Romero','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Ruth Ramirez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Vladimir Rabanales','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Armando Lopez','Ciudad','55005500')",
            "INSERT INTO umg_clientes (nombre, direccion, telefono) VALUES ('Diego Cordoba','Ciudad','55005500')"
        };
    }

    public String[] getInsert_listado_categorias() {
        return new String [] {
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (24,37)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (32,47)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (28,17)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (37,15)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (6,15)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (12,4)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (57,25)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (1,16)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (12,11)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (2,25)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (34,31)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (10,12)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (2,3)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (68,6)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (10,16)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (47,18)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (32,14)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (14,17)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (4,2)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (94,46)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (32,10)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (67,48)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (26,44)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (1,14)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (2,45)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (55,19)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (29,4)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (14,2)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (42,37)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (3,28)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (86,16)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (3,14)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (58,11)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (43,11)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (76,15)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (51,37)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (84,13)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (108,18)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (6,29)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (4,34)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (2,23)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (57,45)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (4,5)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (40,5)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (1,29)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (20,43)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (27,18)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (21,28)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (26,8)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (48,37)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (104,12)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (23,14)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (13,8)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (16,18)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (25,44)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (45,25)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (44,11)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (72,46)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (10,30)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (13,33)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (3,36)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (7,21)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (49,33)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (1,8)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (33,21)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (10,40)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (12,25)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (12,42)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (7,6)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (17,2)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (20,40)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (37,47)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (35,25)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (15,22)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (21,3)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (40,22)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (97,4)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (23,49)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (15,46)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (102,25)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (4,33)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (44,45)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (14,28)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (58,26)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (50,7)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (9,45)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (85,4)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (67,27)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (1,24)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (54,49)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (51,6)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (80,22)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (58,13)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (18,11)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (22,20)",
            "INSERT INTO umg_listado_categorias (id_categoria, id_producto) VALUES (43,26)"
        };
    }
}
