package Ui;


public class StringInsert {
    public String[] getInsert_rols() {
        return new String [] {
            "INSERT INTO rols (id_rol,nombre,descripcion) VALUES (1,'Administrador','Rol de Administrador con descripcion acerca de que hace.');",
            "INSERT INTO rols (id_rol,nombre,descripcion) VALUES (2,'Gerente','Rol de Gerente con descripcion acerca de que hace.');",
            "INSERT INTO rols (id_rol,nombre,descripcion) VALUES (3,'Supervisor','Rol de Supervisor con descripcion acerca de que hace.');",
            "INSERT INTO rols (id_rol,nombre,descripcion) VALUES (4,'Cajero Matutino','Rol de Cajero Matutino con descripcion acerca de que hace.');",
            "INSERT INTO rols (id_rol,nombre,descripcion) VALUES (5,'Cajero Nocturno','Rol de Cajero Nocturno con descripcion acerca de que hace.');",
            "INSERT INTO rols (id_rol,nombre,descripcion) VALUES (6,'Practicante','Rol de Practicante con descripcion acerca de que hace.');"
        };
    }

    public String[] getInsert_usuarios() {
        return new String [] {
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Romero','lucia_romero@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Rebeca Flores','rebeca_flores@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Javier Mazariegos','javier_mazariegos@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ruth Dias','ruth_dias@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Alejandro Ruiz','alejandro_ruiz@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ruth Rojas','ruth_rojas@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Sofia Mazariegos','sofia_mazariegos@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Stefani Dominguez','stefani_dominguez@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Diego Flores','diego_flores@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Aguirre','lucia_aguirre@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Rebeca Torres','rebeca_torres@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Juan Castillo','juan_castillo@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Rebeca Lopez','rebeca_lopez@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Martinez','lucia_martinez@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Angel Carranza','angel_carranza@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Antonio Piedrasanta','antonio_piedrasanta@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Alejandro Romero','alejandro_romero@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Juan Cordoba','juan_cordoba@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Angeles Barrios','angeles_barrios@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ricardo Castillo','ricardo_castillo@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('William Dias','william_dias@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Hector Rodriguez','hector_rodriguez@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Antonio Fernandez','antonio_fernandez@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Recinos','lucia_recinos@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Veronica Piedrasanta','veronica_piedrasanta@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('William Sosa','william_sosa@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Alejandro Flores','alejandro_flores@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Susana Flores','susana_flores@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Pedro Alvarado','pedro_alvarado@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Sofia Giron','sofia_giron@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Angel Monterroso','angel_monterroso@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Susana Sosa','susana_sosa@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ismael Ramirez','ismael_ramirez@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Armando Carranza','armando_carranza@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Aaron Romero','aaron_romero@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Carmen Barrios','carmen_barrios@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Oscar Marquez','oscar_marquez@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Noemi Aguirre','noemi_aguirre@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Jose Sosa','jose_sosa@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('David Lopez','david_lopez@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Maribel Alvarez','maribel_alvarez@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Vladimir Martinez','vladimir_martinez@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Maribel Aguirre','maribel_aguirre@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Daniela Gomez','daniela_gomez@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Pedro Giron','pedro_giron@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Angel Rodriguez','angel_rodriguez@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Sofia Marquez','sofia_marquez@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Pedro Cordoba','pedro_cordoba@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Aaron Ramirez','aaron_ramirez@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ivan Ruiz','ivan_ruiz@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Aaron Rabanales','aaron_rabanales@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Castillo','lucia_castillo@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Daniela Alvarez','daniela_alvarez@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Armando Castillo','armando_castillo@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Oscar Torres','oscar_torres@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Diego Alvarado','diego_alvarado@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Jose Romero','jose_romero@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('William Recinos','william_recinos@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('David Martinez','david_martinez@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Aaron Martinez','aaron_martinez@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('David Monterroso','david_monterroso@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Antonio Siguenza','antonio_siguenza@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Sofia Rodriguez','sofia_rodriguez@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Susana Cordoba','susana_cordoba@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ruth Carranza','ruth_carranza@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Maria Marquez','maria_marquez@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Jose Romero','jose_romero@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Maribel Jimenez','maribel_jimenez@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ismael Mazariegos','ismael_mazariegos@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Antonio Carranza','antonio_carranza@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ricardo Barrios','ricardo_barrios@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Ruiz','lucia_ruiz@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Rebeca Alvarez','rebeca_alvarez@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Angeles Recinos','angeles_recinos@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Javier Gutierrez','javier_gutierrez@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Aaron Monterroso','aaron_monterroso@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('William Castellanos','william_castellanos@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Daniela Perez','daniela_perez@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Pedro Martinez','pedro_martinez@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Rebeca Giron','rebeca_giron@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Aaron Gonzalez','aaron_gonzalez@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Luz Marquez','luz_marquez@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Gutierrez','lucia_gutierrez@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Natalia Aguirre','natalia_aguirre@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Vladimir Aguirre','vladimir_aguirre@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Diego Gutierrez','diego_gutierrez@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ivan Lopez','ivan_lopez@miumg.edu.gt','MTIzNDU=',2);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Angel Romero','angel_romero@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Juan Jimenez','juan_jimenez@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Luz Gutierrez','luz_gutierrez@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Ismael Recinos','ismael_recinos@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Lucia Gonzalez','lucia_gonzalez@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Maribel Romero','maribel_romero@miumg.edu.gt','MTIzNDU=',5);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Susana Carranza','susana_carranza@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Veronica Rojas','veronica_rojas@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Daniela Lopez','daniela_lopez@miumg.edu.gt','MTIzNDU=',3);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Angeles Rabanales','angeles_rabanales@miumg.edu.gt','MTIzNDU=',1);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Carolina Castro','carolina_castro@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Stefani Giron','stefani_giron@miumg.edu.gt','MTIzNDU=',4);",
            "INSERT INTO usuarios (nombre, correo_acceso, pw, rol) VALUES ('Estrella Mazariegos','estrella_mazariegos@miumg.edu.gt','MTIzNDU=',3);"
        };
    }

    public String[] getInsert_unidades_medida() {
        return new String [] {
            "INSERT INTO unidades_medida (nombre) VALUES ('Onza');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Libra');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Arroba');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Kilogramo');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Gramo');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Miligramo');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Tonelada');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Sixpack');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Lata');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Botella');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Caja');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Docena');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Decena');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Ciento');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Centimetro');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Galon');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Pie');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Pulgadas');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Yarda');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Arroba');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Litro');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Medio Litro');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Duo Pack');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Pieza');",
            "INSERT INTO unidades_medida (nombre) VALUES ('Kit');"
        };
    }

    public String[] getInsert_proveedores() {
        return new String [] {
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Malher','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Cerveceria Centroamericana','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Adeph','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Cruz Verde','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Farmacias del Ahorro','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Wallmart','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Paiz','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Despensa Familiar','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Toyota','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Mazda','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Hyundai','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Bodega Central','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('ADOC','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Par Dos','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Gallo','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Unilever','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Colgate','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Coca Cola','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('McDonalds','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Burger King','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Wendys','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Pepsi','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Dos Pinos','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Quaker','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Pozuelo','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Protex','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Bimbo','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Axion','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Bremen','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Tang','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Nescafe','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Musum','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Ina','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Salvavidas','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Charles','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Tacorazon','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('HP','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Dell','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('MSI','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Aorus','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Lenovo','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Kingston','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('XPG','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Corsair','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Cooler Master','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Adata','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('EVGA','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Razer','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Logitech','Ciudad de Guatemala',0);",
            "INSERT INTO proveedores (nombre, direccion, telefono) VALUES ('Asus','Ciudad de Guatemala',0);"
        };
    }

    public String[] getInsert_ext() {
        return new String [] {
        };
    }
}